version: 1

# Checkmarx configuration file
#
# https://docs.checkmarx.com/en/34965-68549-configuring-projects-using-config-as-code-files.html
checkmarx:
  scan:
    configs:
      sast:
        # Exclude test directories
        filter: "!src/test/**"
