name: Test Authenticator

on:
  workflow_dispatch:

jobs:
  placeholder:
    name: Placeholder Job
    runs-on: ubuntu-24.04

    steps:
      - name: Placeholder Step
        run: echo "placeholder workflow"
